---
- name: Base setup and update of the system
  hosts: ip
  become: true

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce', 'docker-compose']
      state: present
      update_cache: yes

  - name: add user mod
    command: usermod -aG docker user
    become: true

  - name: Unconditionally reboot the machine with all defaults
    reboot:

  - name: Ensure the docker service is running
    service:
      name: docker
      state: started
    become: yes
